server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-exception: false
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:h2:mem:h2DB;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}

web-client:
  connect-timeout: 10s
  read-timeout: 10s
