name: Main CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          java-version: 11
          distribution: zulu
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
